In [1]:
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('heart_failure_clinical_records_dataset.csv')

In [3]:
data.shape

(299, 13)

In [4]:
data.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [5]:
data

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    int64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    int64
 12  DEATH_EVENT               299 non-null    int64
dtypes: float64(3), int64(10)
memory usage: 30.5 KB

In [7]:
data.duplicated().sum()

0

In [8]:
data.isna().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [9]:
X = data.drop("DEATH_EVENT", axis=1)
y = data.DEATH_EVENT

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=.20, random_state=42)

In [11]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

LogisticRegression()

In [12]:
log_reg.coef_

array([[ 5.93120538e-02, -8.32482859e-05,  1.10957040e-04,
         5.19143173e-04, -6.68663740e-02, -4.94407874e-04,
        -1.44001729e-06,  7.65118814e-03,  3.48309757e-03,
        -7.55388815e-04, -3.19013334e-04, -2.07194896e-02]])

In [13]:
y_pred = log_reg.predict(X_train)

In [14]:
pd.DataFrame({'y_train':y_train, 'y_pred':y_pred})

     y_train  y_pred
6          1       1
183        1       0
185        1       0
146        0       0
30         1       1
..       ...     ...
188        0       0
71         0       1
106        0       0
270        0       0
102        0       1

[239 rows x 2 columns]

In [15]:
correct = 0
for y,yp in zip(y_pred, y_train):
    if y==yp:
        correct+=1
correct/len(X_train)

0.8410041841004184

In [16]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix

In [17]:
confusion_matrix(y_train,y_pred)

array([[154,  14],
       [ 24,  47]], dtype=int64)

In [18]:
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.92      0.89       168
           1       0.77      0.66      0.71        71

    accuracy                           0.84       239
   macro avg       0.82      0.79      0.80       239
weighted avg       0.84      0.84      0.84       239

In [19]:
y.value_counts()

AttributeError: 'numpy.int64' object has no attribute 'value_counts'

In [22]:
y = data["DEATH_EVENT"]

In [23]:
y.value_counts()

0    203
1     96
Name: DEATH_EVENT, dtype: int64